name: uge
dependencies:
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - nvidia::pytorch-cuda=11.8 # nvcc -V !!!
  - conda-forge::kornia
  - conda-forge::matplotlib
  - conda-forge::numpy
  - conda-forge::opencv
  - anaconda::pillow
  - anaconda::jupyter
  - conda-forge::nbclassic
  - conda-forge::tqdm
  - conda-forge::scikit-learn
  # hugging face
  - conda-forge::transformers
  - conda-forge::datasets